name: Deploy to EU WEST Master

on:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  tools: composer:v2
                  coverage: none
            - name: workflow done
              run: echo "DONE!!!"
